-- 3. Comprobación de la estructura creada

SELECT
    TABLE_SCHEMA AS esquema,
    TABLE_NAME AS tabla
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;
GO

SELECT
    tc.TABLE_NAME AS tabla,
    tc.CONSTRAINT_NAME AS restriccion,
    tc.CONSTRAINT_TYPE AS tipo
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc
ORDER BY tc.TABLE_NAME, tc.CONSTRAINT_TYPE;
GO

PRINT 'Base de datos y estructuras creadas correctamente.';
GO